### ISSUE TITLE
Request params are not reported for plain Rack apps

### ISSUE THREAD

**Issue by mkarganov** [rollbar/rollbar-gem#1033]
Hi, while integrating Rollbar with Hanami I noticed that after reporting to Rollbar - scopes are not passed properly. After investigating the issue I finally found the problem:

When `scoped` method called first time in middleware: https://github.com/rollbar/rollbar-gem/blob/63c68eed6a8066cdd8e09ab5429728d187482b12/lib/rollbar/middleware/rack.rb#L15-L20

notifiers get correctly replaced by `scoped` method logic, but inside passed block there is a `response = @app.call(env)` which calls `Rack::Builder`:
https://github.com/rollbar/rollbar-gem/blob/63c68eed6a8066cdd8e09ab5429728d187482b12/lib/rollbar/middleware/rack/builder.rb#L11-L22

`Rack::Builder` on it's own calls `scoped` again but resets `notifier` before:  https://github.com/rollbar/rollbar-gem/blob/63c68eed6a8066cdd8e09ab5429728d187482b12/lib/rollbar/middleware/rack/builder.rb#L12

This results to overwriting original notifier with original scope with reseted one. And not delivering request parameters at all to Rollbar

Removing `Rollbar.reset_notifier!` solves the problem.

Is it safe to remove it? https://github.com/rollbar/rollbar-gem/pull/1034

**Comment by waltjones** [comment]
These are designed to only use one or the other, not nested. To only use the builder middleware, remove `use Rollbar::Middleware::Rack` wherever it's been added.

To only use the Builder plugin, add `disable_rack_monkey_patch = true` to your Rollbar config.

These are both described here: https://docs.rollbar.com/docs/rack

Removing `Rollbar.reset_notifier!` isn't recommended because it ensures the notifier is in a known/clean state.

**Comment by mkarganov** [comment]
Thanks! will check it!

**Comment by waltjones** [comment]
Good to hear!
