### ISSUE TITLE
sidekiq + async_json_payload is not set

### ISSUE THREAD

**Issue by netwire88** [rollbar/rollbar-gem#1088]
Hi,
I'm using rollbar 3.3 and sidekiq 6.3.1, when I enable `config.use_sidekiq` in `rollbar.rb`, I don't think rollbar is using the `rollbar` queue for sending error messages. I also noticed this:

"configured_options": "not serialized when async_json_payload is not set"

Do I need to enable `config.async_json_payload` as well?

**Comment by waltjones** [comment]
I haven't seen an issue with the `rollbar` queue and have tested with 6.2.2. The queue needs to exist on sidekiq, e.g.
```
bundle exec sidekiq -q rollbar
```

`config.async_json_payload` is optional. Performance is improved when it is set because the payload is serialized/deserialized fewer times. It defaults to unset for back compatibility -- Existing plugins may expect to see a ruby object rather than a JSON string.

**Comment by waltjones** [comment]
The way I've done it is to watch the sidekiq log. I think sidekiq only logs to stdout, so you need to watch in the console or redirect it to a file. Also I don't recall whether the default log level is noisy enough.

**Comment by waltjones** [comment]
Closing. Reopen if this still needs attention.
