### ISSUE TITLE
It would be awesome if Rollbar.configuration.scrub_fields could take a lambda like Rails.application.config.filter_parameters

### ISSUE THREAD

**Issue by jtzemp** [rollbar/rollbar-gem#139]
I've got an extensive list of symbols and lambdas in my Rails.application.config.filter_parameters list (lots of sensitive data). I'd love to just be able to do this:
`Rollbar.configuration.scrub_fields = Rails.application.config.filter_parameters` and have it all work out the way it'd make sense.

I asked on the website via the Olark chat and got the answer back that it doesn't do it and that I should create an issue here.

If I get time, I'll work on submitting a PR.

Thanks!

JT

**Comment by skippy** [comment]
hey @jondeandres 

I'm looking at the ability to scrub data.  This functionality request (being able to use lambdas) is close, but I would like to take it one step further.  Instead of listing a blacklist, I would like to flip it and create a whitelist.  ie, ONLY allow these fields to go through, everything else would either be scrubbed.  Does that make sense?  Let me know if you want to discuss that in this ticket or if I should create a new ticket.  thanks

**Comment by jondeandres** [comment]
@skippy 

We can do something with this, yes. We'll consider it soon. This can be enough for you?

```ruby
Rollbar.configure do |config|
  config.allowed_parameters = %w[id username item_id]
end
```

For example?

**Comment by skippy** [comment]
ah, interesting.  Probably not, but I'm not 100% sure.  

The concern is protected data leaking out.  I can think of two clear pathways outside of `allowed_parameters`:
* rollbar inserts info into the data object that needs to be scrubbed.  Currently, it inserts `user_ip`, which is considered protected data, but it could be other things in the future.

* all the various objects could leak data, such as `request`, `sessions`, `cookies`, `exception.message`, etc.  One can easily make the argument that such objects are under my control and that I shouldn't be an idiot and do something like `throw StandardError.new("user123-4567-890 failed") #woops!  that is a social security number!`, or put protected data into a cookie `cookies[:ccn]`, but it is amazing how hard it is to hold fast on that as the team and system complexity grow.

my example may be too extreme.  But if someone use `config.allowed_parameters = %w(user_ip)` they may think they are all set, but the `user_ip` shows up at rollbar anyway.

I ended up monkey patching this through the `config.async_handler` because it passes the full payload through there.  I wonder if making that an explicit option, such as
```ruby
  Rollbar.configure do |config|
    config.pre_process = Proc.new { |payload| Corp::ExceptionHandler.scrub(payload) }
  end
```
could hit most use cases?

**Comment by jondeandres** [comment]
@skippy it's interesting, yes. we can offer an interface to let the user control and scrub data in a more detailed way. it's nice. we'll consider this idea.

however, take account that in your own example, are you who is adding on one side critical data into cookies, class.message or others...and on other side you are using `Corp::ExceptionHandler.scrub` to remove that same data.

I agree on having more flexibility for this, but I'm not sure actually is super useful. If we could pass the current request object into those callbacks, that'd be really nice.

Thanks for the idea @skippy! We'll take a look :smile:.

**Comment by skippy** [comment]
> however, take account that in your own example, are you who is adding on one side critical data into cookies, class.message or others...and on other side you are using Corp::ExceptionHandler.scrub to remove that same data.

oh, I wasn't saying I was going to do that (!!)... I was just commenting on how easy it is to leak data by mistake.  

> I agree on having more flexibility for this, but I'm not sure actually is super useful. 

well, it gives us quite a bit of control of the object before it goes out; that has some bonus.  But yes, passing in the request object directly would be sweet.  (enrichment!  like adding the `X-REQUEST_ID` would be killer; I'm doing that now but via a hacky thread-local variable.)

**Comment by peashutop** [comment]
Hi folks -- just wondering if any of the @skippy's ideas above have been implemented? Thanks!

**Comment by philkcw** [comment]
@jondeandres , having a whitelist of params would be a valuable option for us because it would mean no extra Rollbar configuration would have to be done as our applications grow.  Is that on your roadmap?

**Comment by jondeandres** [comment]
@philkcw is not in our inmediate roadmap but we'll add it. I hope we can release something soon.

**Comment by djurre** [comment]
@jondeandres Whitelisting parameters would be useful for us as well, has there been any progress on this?

**Comment by jondeandres** [comment]
Hey @djurre, we didn't progress yet on this, but we are trying to prioritize it. Once we work on it we'll ping all of you.

Thanks pushing this!

**Comment by rokob** [comment]
I don't think adding a simple whitelist should be that much work so doing that is something we can get out relatively quickly. For more complicated scenarios, we do have the [transform hook](https://github.com/rollbar/rollbar-gem#transform-hook).

**Comment by djurre** [comment]
Whitelisting would still be a very useful feature for us, so it would be great if this could be reopened.

**Comment by djurre** [comment]
Great, thanks!
