### ISSUE TITLE
Improve internal error handling

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-gem#177]
Our current `report_internal_error` and `send_failsafe` functionality leaves something to be desired...

Quick list of improvements to make:

- in `report_internal_error`, use a fresh scope (i.e. one without all of the context already there) to execute `build_payload`. (As it is now, we try again with the same scope, but that's likely to cause the same exception that make the report fail in the first place.)
- in `report_internal_error`, we should be carefully logging the exception at the beginning of the function, so that it at least will appear in the rails log.
- all of this should also try hard to log the original data that the developer was trying to report

**Comment by adambair** [comment]
:+1: I just upgraded to Rails 4 and Rollbar ended up swallowing a few key exceptions which made solving these issues fairly... challenging ;)

**Comment by fabn** [comment]
Any news on this? I just upgraded to resolve #195 I hope that issue is fixed.

In any case have an error report which only states `Failsafe from rollbar-gem: build_payload in exception_data` is not useful, you should really enhance the internal error report, maybe writing a file with details or something like that.

In this way one could check on server what's happening when get those weird errors.

**Comment by brianr** [comment]
I believe this is resolved by https://github.com/rollbar/rollbar-gem/pull/354 - thanks @fabn for that! Going to close this issue.
