### ISSUE TITLE
Allow for 'fingerprint' field

### ISSUE THREAD

**Issue by JorgeRdg** [rollbar/rollbar-gem#201]
I'm using the gem to monitorize some stuff and I'd like to get notifications of every single occurrence of an item. However, I haven't managed to achieve it as Rollbar keeps grouping them even though I attach stuff like timestamps.

Reading through the documentation, I've seen that this can be achieved by specyfing the 'fingerprint' field in the report. However, this functionality doesn't seems to exist in the gem. Am I right?

That would be a very nice add-in for this gem and a really needed for me!

**Comment by brianr** [comment]
Hi @JorgeRdg - thanks for asking; the docs definitely don't cover this well. Assuming you're talking about direct calls you are making to `Rollbar.error`, `Rollbar.warning`, etc., you can set the fingerprint like this:

```
Rollbar.scope({:fingerprint => "fingerprint here"}).error(err)
```

Is that what you tried?

**Comment by JorgeRdg** [comment]
I didn't know of the `scope` option. Thank you! That seems to do the trick ;)

**Comment by wangyuesong** [comment]
Hi! I recently read through the docs(https://rollbar.com/docs/grouping-algorithm/) and Customizing Grouping in Code section really confused me since it said to support only Browser JS and python. But actually this ruby gem do support adding fingerprint using Rollbar.scope({:fingerprint => "fingerprint here"}).error(err).

Please revise the doc if needed.

**Comment by brianr** [comment]
Thanks @wangyuesong ! I've updated that doc to add examples for a few other languages, and better default text for the rest.
