### ISSUE TITLE
Stop monkey-patching Rack::Builder

### ISSUE THREAD

**Issue by joneslee85** [rollbar/rollbar-gem#305]
IMHO monkey-patching Rack::Builder is a bad idea as it might alter the behaviour of many rack-based frameworks which could lead to unexpected bugs. Please fix me if I am wrong here, I think the solution is a ExceptionReporter middleware at the end of the middleware stacks and exceptions from higher middlewares will bubble down the stack.

I am happy to offer a PR if this proves useful for this project.

**Comment by jondeandres** [comment]
@joneslee85 we already have a issue for this, https://github.com/rollbar/rollbar-gem/issues/157.

Our main problem is that we don't want to break the actual reporting the customers could have. So we thought to add this in a next more important release. Of course you can open a PR for this and we'll evaluate it!

I close this one since we already had one.

Thanks!
