### ISSUE TITLE
[security] Read secrets from `config/secrets.rb`

### ISSUE THREAD

**Issue by paulmenzel** [rollbar/rollbar-gem#384]
Currently, the generator creates files with the access tokens `app/views/shared/_rollbar.haml` and `config/initializers/rollbar.rb`.

Please update them, so that it’s read from `config/secrets.rb`, to not have people check in their secrets into the repository.

**Comment by jrjamespdx** [comment]
Unfortunately I don't think this would work across the board.  I think the way Rollbar does it now is the best way of handling it given that there really isn't a SINGLE agreed upon convention for dealing with environment variables of a sensitive nature.

Also, I'm not sure if you meant to say config/secrets.yml instead of config/secrets.rb but I'll mention both below just to be sure.

1.  **secrets.yml**

-  is only auto generated in Rails starting in version 4.1 so those using older Rails versions won't have this file (unless they created it by hand previously)  _*I think GitHub is still on a Rails 3.X version as an example_

-  secrets.yml isn't added to any tracking exclusion by default, so technically a dev would still have a chance to place production values there and then push them to a public repo

2.  **secrets.rb or any other custom secrets/local_env type file**

- no single convention for doing this, so configuration is left to the end user, this means most implementations are unique so shoving them into an arbitrary file won't work across the board

- still requires dev to manually add the file to their version tracker ignore list

All-in-all, the developer has the option to not generate the keys in the file and is left to configure things based on their own business needs.

I'd love to discuss this more and find out more about your proposed idea, @paulmenzel :)
