### ISSUE TITLE
undefined method `split' for nil:NilClass occur in assets:precompile

### ISSUE THREAD

**Issue by AknEp** [rollbar/rollbar-gem#411]
In my heroku enviroment, `undefined method `split' for nil:NilClass` was occurred in `assets:precompile`.

I found `Rake::VERSION` and `RAKEVERSION` is nil. so rollbar gem crashes in `Rollbar::Rake.patch!`

I don't know why Rake Version const was not defined ...
my Gemfile.lock has below.., and bundle install command success.

```
rake (11.1.1)
```

but, I think rollbar should be more robust.

**Comment by jondeandres** [comment]
Hi @AknEp, this is resolved in lasts releases of the gem. Please try to update to the last one. THe fix is in this PR, https://github.com/rollbar/rollbar-gem/pull/397.

Rake 11.x was release the 9th o march and we fixed it on 10th. We know this may has caused problems to you, so we are sorry.

Thanks.

**Comment by AknEp** [comment]
oops! Thank you for your quick response. sorry for my no-checking other issues.

but I think similar problem should occur, so #397 it not enough. I'll send PR.
