### ISSUE TITLE
Error when compiling assets after upgrade from 2.10.0 to 2.11.0

### ISSUE THREAD

**Issue by fredngo** [rollbar/rollbar-gem#457]
After upgrading the rollbar gem from 2.10.0 to 2.11.0, I'm getting this error when deploying to Heroku:

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        E, [2016-04-30T16:29:05.581224 #395] ERROR -- : Error trying to load plugin 'rails-rollbar.js': LocalJumpError, unexpected return
remote:        Asset precompilation completed (45.30s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote:        E, [2016-04-30T16:29:50.778210 #546] ERROR -- : Error trying to load plugin 'rails-rollbar.js': LocalJumpError, unexpected return
remote: 
```

**Comment by mattbrictson** [comment]
Same error here. Downgrading to rollbar 2.10.0 fixes the issue.

**Comment by jondeandres** [comment]
Hey there, thank you for reporting this. This was caused since you didn't have `config.js_enabled = true` enabled and we had a `return` statement inside a Proc when we shouldn't.

We've release 2.11.1 version of the gem with a fix for that, https://github.com/rollbar/rollbar-gem/commit/b85f09aaf92c3e75d1b58fd31a28cff143ee7d67. This should be resolved now.

Just as explanation, the rollbar.js plugin loading failure wouldn't have impacted in the behavior of your project.

Thanks again for reporting this.
