### ISSUE TITLE
Middleware/Rack/Rollbar::Middleware::Rails::RollbarMiddleware#call very slow

### ISSUE THREAD

**Issue by jamesfzhang** [rollbar/rollbar-gem#486]
New Relic says the average call for this method takes over 8 seconds. Any idea?
<img width="429" alt="screen shot 2016-06-07 at 5 58 23 pm" src="https://cloud.githubusercontent.com/assets/2057670/15879498/a04b252e-2cd9-11e6-891a-938e3a6bd8b1.png">

**Comment by jondeandres** [comment]
@jamesfzhang it may be related to delay issues in our API since that middlewares sends a POST request when an error is found. In general you shouldn't have this behavior.

With this, we always recommend use any of the delay handers we support, take a look at https://github.com/rollbar/rollbar-gem#asynchronous-reporting.

If you have any other problem please ping us.

Thanks!

**Comment by zakthompson** [comment]
Sorry for necro-ing, but I'm actually experiencing something very similar - and we are using asynchronous reporting via DelayedJob.  However, this call doesn't appear to be async, and appears to hang until it times out.

<img width="1158" alt="screenshot 2016-12-08 16 10 49" src="https://cloud.githubusercontent.com/assets/1450527/21027917/eacb0822-bd60-11e6-8614-69980348ae98.png">

I'm wondering if in our case it's something to do with the interaction between Rollbar and [rack-timeout](https://github.com/heroku/rack-timeout), because when one of these long calls occurs, it sets off a chain of them which can take down our entire server.

**Comment by jondeandres** [comment]
Hi @zakthompson, thanks for the report. It's quite strange having that duration time on our call. Are you sure the time you are wasting is in the middleware itself?

Did you try running the on-live profiler that New Relic has? That will give you accurated stats about the time you are wasting on each method.
