### ISSUE TITLE
Middleware inserts JavaScript before charset meta tag

### ISSUE THREAD

**Issue by spdawson** [rollbar/rollbar-gem#546]
According to e.g. [this](https://www.w3.org/International/questions/qa-html-encoding-declarations.en), the `charset`-declaring `<meta>` tag must occur entirely within the first 1024 bytes of the document.

However, the Rollbar middleware inserts the JavaScript tags immediately after the opening `<head>` tag; this causes validation errors for HTML documents that include the auto-inserted Rollbar JavaScript tags.

**Comment by stclairdaniel** [comment]
Thanks for bringing this to our attention. We'll take a look at it and get back to you with more information.

**Comment by rokob** [comment]
Related to #569

**Comment by dignoe** [comment]
It's been almost a year and this issue hasn't been fixed. It seems pretty trivial to fix this... instead of searching for `body.index(/<head\W/)`, just search for `<meta charset="foo">` or `<meta http-equiv="Content-Type" content="bar">` and inject the script after that. If those aren't found, fall back to `<head`. Can we please get this fixed soon?

**Comment by rokob** [comment]
We always are willing to take pull requests to fix issues. This one in particular if a straightforward fix is possible would be a good candidate for a pull request. I am going to work on the js injection right now, so I will take this one.
