### ISSUE TITLE
Missing coverage in Codacy

### ISSUE THREAD

**Issue by coryvirok** [rollbar/rollbar-gem#583]
https://codeclimate.com/github/rollbar/rollbar-gem

Looks like @jondeandres had this working at one point or at least tried to get it working.

**Comment by coryvirok** [comment]
@jondeandres any thoughts on getting test coverage reporting to CodeClimate?

**Comment by jondeandres** [comment]
I had enabled it on our spec_helper.rb file, https://github.com/rollbar/rollbar-gem/blob/master/spec/spec_helper.rb#L1-L14, but the required gems are not present in our gemfiles, so that may be the reason because https://codeclimate.com/repos/537e61f8e30ba05e65002eaa/settings/test_reporter is empty.

I will take a look at this.

**Comment by coryvirok** [comment]
I haven't been very happy with CodeClimate but Codacy seems great. Let's set up test coverage there. https://www.codacy.com/app/Rollbar/rollbar-gem/settings/coverage#IntegrationsTab

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by coryvirok** [comment]
Reopening so that we can get coverage info reported to Codacy.

**Comment by waltjones** [comment]
With the linked PR, this is working now.
