### ISSUE TITLE
`Rollbar.scoped` does not work as advertised

### ISSUE THREAD

**Issue by pawlik** [rollbar/rollbar-gem#593]
This will result in `data.important` being connected with the exception occurrence: 
```
    Rollbar.scope!({data: {important: '123'}})
    raise StandardError.new('some message')
```
but this: 
```
    Rollbar.scoped({data: {important: '123'}}) do
       raise StandardError.new('some message')
    end
```
will not send extra data at all.

In the README it's not written that it should work, but here https://github.com/rollbar/rollbar-gem/issues/500 @jondeandres claims that it should work. Is it a bug? If not - could it work that way in next versions? There are some bugs which are hard to trace, the possibility to add extra info but not silence the exception would be useful. (And mutating scope with `Rollbar.scope!` is little bit scary in big projects). 

We use `2.14.0` version of the gem.

**Comment by jondeandres** [comment]
Hey @pawlik, thanks for opening this issue. Maybe I've explained wrongly other times, I'll try to explain it again.

`Rollbar.scoped!` mutates the scope for the current iteration (a request, job, etc...) handled by our middlewares. So at any point you can change it and after that, the errors sent will have that scope.

`Rollbar.scoped` changes the scope inside the block passed. But that means that the reports need to be sent inside that block. So, exceptions raised on that scope don't attach the scope in the block. I think this was the behavior you expected.

In order to do that we would need to redefine `raise` so we can attach the scope to the exception and use it when reporting the error. It's not a bad idea, but I think it adds lot of complexity to the behavior, but it's something we may discuss at Rollbar.

**Comment by pawlik** [comment]
Thanks @jondeandres for the clarification. 

Whatever way to attach extra info to raised exception without silencing:
```ruby
rescue => e 
   Rollbar.error(e, {extra: 'data'})
end
````
nor duplicating 
```ruby
rescue => e 
   Rollbar.error(e, {extra: 'data'})
   raise e
end
```
would be quite useful. Either the approach suggested above, or what's suggested in https://github.com/rollbar/rollbar-gem/issues/572 or even something like this
```ruby
rescue => e
  Rollbar.error_and_fail(e, {extra: 'data'})
end
```
I let you decide what's the most feasible approach :)
