### ISSUE TITLE
scrub_fields too broad

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-gem#614]
when added a param to scrub fields such as "name", every field that had the substring called "name" was obfuscated. so something like "first_name" or "last_name" etc would be obfuscated. Can this be more specific?

**Comment by cabello** [comment]
Indeed, there should also be a way of whitelisting parameters, since `:scrub_all` is an option.

I have sidekiq jobs being scrubbed right now, things like: `job.class`, `job.created_at`, `job.enqueue_at`, `job.error_class`, `job.error_message`, etc.

**Comment by rokob** [comment]
It appears we convert the parameters into a regex and match for scrubbing rather than doing string equality. I have to imagine that some people probably rely on this and put regexs in those scrub fields. We could do a few different things:

1. Switch to exact string matching
2. Keep doing what we are doing, but add a whitelist for exact matches to not scrub
3. Add a separate list of regex fields so we support both exact match and regex in case someone is relying on the fact that we use regexs.

I think we should switch to exact string matching, but will have to call it out in the release so that people don't leak data if they were relying on scrub_fields being used as regular expressions.

The reason we treat them as regular expressions appears to be because we do something like `scrub_fields.join('|')` and match on that, which may or may not be faster than a loop through scrub_fields with an `==` test.

**Comment by rokob** [comment]
Okay so I'm back around to this. Because Rails uses this regex approach (i.e. http://api.rubyonrails.org/classes/ActionDispatch/Http/FilterParameters.html) and we have been doing it, I am reluctantly to switch to exact string matching. Therefore, I think (2) is the way to go adding a whitelist of exact matches not to scrub.

**Comment by cabello** [comment]
Any updates on this? How easily could we do whitelisting? I would prefer to opt-in for non-scrubbed data than opt-out.

**Comment by rokob** [comment]
I'm working on adding a configurable list of keys that will not be scrubbed based on an exact match

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by cabello** [comment]
This is still an issue for me... I actually tweeted at Rollbar recently asking for an update.
