### ISSUE TITLE
Sidekiq and jobs that are expected to fail

### ISSUE THREAD

**Issue by cabello** [rollbar/rollbar-gem#616]
Hi,

Because of eventual consistency and other reasons I have jobs that are expected to fail for a while raising 404 Resource Not Found until they succeed, I am already using `config.sidekiq_threshold = 4` (4 retries means just a few minutes), since this is a global setting I don't want to set it to too high, e.g. `18`, because I don't want new errors to go unnoticed and take days to get to Rollbar.

Any suggestions and/or ideas on how to silence these errors?

One of my ideas is to disable the Rollbar error handler https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/sidekiq.rb#L16 and call the same method `Rollbar::Sidekiq.handle_exception(context, e)` using the `sidekiq_retries_exhausted`, this means I would only get reports from these specific workers when they are dead.

One other option would be to enhance Rollbar to allow `sidekiq_threshold` to be redefined per Worker, my couple workers that are expected to fail would be configured with more robust value while all the other ones could go as low as zero.

Thanks,

**Comment by cabello** [comment]
The other thing I would like to do is to fail a job (causing a retry) but do not report to Rollbar, for example I would like to retry a job that raised `RestClient::ResourceNotFound` without sending the error to Rollbar.

**Comment by cabello** [comment]
I "solved" this issue by wrapping the exception that was expected by my job `RestClient::RecordNotFound` into a specialized exception `EventualConsistencyException` and adding it to the ignore configuration `initializers/rollbar.rb`:
```ruby
config.exception_level_filters['EventualConsistencyException'] = 'ignore'
```

**Comment by rokob** [comment]
I believe that using `scope!` in your perform method should be sufficient to set per worker thresholds, for example using the example in the README:

```
class NotificationJob
  include Sidekiq::Worker

  def perform(user_id)
    Rollbar.scope!(:sidekiq_threshold => 18)
    Notification.send_to_user(user_id)
  end
end
```

To be able to retry a job due to an exception and not report to Rollbar your approach of using a specific exception for this would seem to be a reasonable approach. I am not sure what else to offer as a solution if you want some exceptions reported but others not reported and yet both to cause retries. To do that, there needs to be either some configuration input with a wrapped exception or using the `before_process` hook and throwing a `Rollbar::Ignore` exception based on the inputs for the cases you want to ignore.

**Comment by gingerlime** [comment]
I know this is an old issue, but I'm looking at a similar issue now. Essentially, only report errors after a certain number of retries, so trivial errors that "self-heal" can be ignored.

I can see that there's a config to set a threshold for the number of failures before they get reported to Rollback, but this seems to cover (only?) Delayed Jobs

> You can also change the threshold of job retries that must occur before a job is reported to Rollbar:
> 
> `config.dj_threshold = 2 # default is 0`

Is there something equivalent for Sidekiq without delayed job?
