### ISSUE TITLE
JSON body params not available in rollbar

### ISSUE THREAD

**Issue by sdhull** [rollbar/rollbar-gem#746]
No idea what it's related to exactly and I don't have time to debug the gem unfortunately, however I can tell you this:
* we're using ember.js on the frontend
* `ACCEPT` & `CONTENT_TYPE` headers are both set to "application/vnd.api+json"
* `params` shown in rollbar only reflect route information (controller, action, id) and are completely missing the JSON from the request body
* rollbar gem version 2.15.5

**Comment by rivkahstandig3636** [comment]
Hi there, Can you upgrade to the latest version of the gem and see if this is still an issue for you? If it is we can re-open this issue.

**Comment by scudco** [comment]
Hi @rivkahstandig3636 

We ran into this issue again and took the time track down the root cause.

The rollbar gem currently has two problems when it comes to evaluating the `Content-Type` and `Accept` headers within `json_request?` https://github.com/rollbar/rollbar-gem/blob/3c66a47be634fb56a32a390ec3b8e32e2b6c49ed/lib/rollbar/request_data_extractor.rb#L210

1. It should be checking that the `Content-Type` is any kind of JSON. This would mean that `application/json`, `application/vnd.api+json`, etc are all considered JSON.
2. The `Accept` header must be read via `rack_req.env['HTTP_ACCEPT']`.

We've patched this locally for ourselves. I'll open a PR shortly.
