### ISSUE TITLE
Duplicate Exception for Configuring Rails.logger to extend Rollbar::Logger

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#771]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/17883415297

The user is getting dupes of the same exception, one at the error level, one at the critical level for this configuration:
```
require 'rollbar/logger'

Rollbar.configure do |config|

  config.access_token = ENV['ROLLBAR_ACCESS_TOKEN']

  config.enabled = false if Rails.env.test?

  config.use_async = true

  config.environment = ENV['ROLLBAR_ENV'].presence || Rails.env
end

Rails.logger.extend(ActiveSupport::Logger.broadcast(Rollbar::Logger.new))
```

**Comment by ArturMoczulski** [comment]
This is expected behavior actually.

The first time, the exception is being reported through the default middleware mechanism. This is more complete reporting that will include Rails context information.

The second time, Rails logger logs a message about the exception to Rails' log. Since it has been extended with `Rails.logger.extend`, that logging will also trigger a report to Rollbar with the same log message. However, this time it will be only the message, not including more in-depth exception data.

Removing this message duplication creates a risk of underreporting or confusing / risky logic for the logger. I'd rather accept overreporting with duplicated exception message rather than doing this.

**Comment by esaborit4code** [comment]
Thanks for the explanation, @ArturMoczulski.

I think it would be nice to mention this behaviour in the docs (https://docs.rollbar.com/docs/ruby#section-logger-interface) as it may be unexpected for others.

In addition, I realized that the duplicated critical errors are reported as two separate items: a first one containing the error message and a second one with the traceback (not as traceback but as message).
