### ISSUE TITLE
Empty rescue-raise blocks

### ISSUE THREAD

**Issue by p1366** [rollbar/rollbar-gem#855]
There are multiple empty `rescue raise` blocks like [this](https://github.com/rollbar/rollbar-gem/blob/v2.19.2/lib/rollbar/delay/sidekiq.rb#L21-L27).

What's the goal?

AFAIK, there is no difference between
```ruby
begin
  payload_raising_some_error
rescue
  raise
end
```
and
```ruby
payload_raising_some_error
```

**Comment by rokob** [comment]
Looking at the history, there is no good reason other than possibly being a form of documentation that we are aware that the method we are calling can raise and that allowing it to raise without rescuing it is the desired behavior. This is mostly in the async handlers where we want to raise to allow the handlers to retry jobs. It used to be the case that these methods swallowed exceptions so this change of allowing them to bubble up was intentional. In at least one case we still swallow the exception intentionally but it is documented why.

**Comment by p1366** [comment]
Yep, I saw the history and the PR, which added `rescue-raise`. The main(and right) retry logic is in `Rollbar.process_from_async_handler` method: `Rollbar.silenced` block with re-raise. The method has very detailed description.

Two things confuse me:
1. Exceptions are not free and useless `rescue-raise` is just CPU wasting.
2. "Refactoring", when one of last commit changes `rescue-raise` blocks to another useless form:
https://github.com/rollbar/rollbar-gem/blob/3c66a47be634fb56a32a390ec3b8e32e2b6c49ed/lib/rollbar/delay/sidekiq.rb#L20-L23

Is there a chance to get rid of the `rescue-raise` blocks(leave only comments) ?

**Comment by waltjones** [comment]
@p1366 that's just cleaning up some of the many rubocop issues in the code base. Even if it doesn't materially change the issue you raise (no pun intended), reducing these does help contributors avoid waking up a bunch of latent rubocop issues that then fail in CI.

To your earlier comment, yes I would think these rescues could be removed.

**Comment by p1366** [comment]
@waltjones Yes, I completely understand the rubocop PR reason.
I just tried to push thought that the useless blocks should be removed as they require useless refactoring.
Sorry if I was too intrusive :)

**Comment by waltjones** [comment]
@p1366, not at all! Thanks for bringing up the issue.
