### ISSUE TITLE
Is it possible to ignore the 'Job has failed and won't be retried' error when using delayed job 

### ISSUE THREAD

**Issue by RobWillison** [rollbar/rollbar-gem#863]
Hi,

We are using delayed job with Rollbar and have set some exception level filters to ignore exceptions that we do not want logging to Rollbar and it works really well. However we are still getting errors logged when the job fails after being tried 5 times even when the exception matches one of the `exception_level_filters`.

I think this is because when the delayed job failure hook is called you only have access to the `last_error` string and not the exception object so you don't know what the exception class was to be able to apply any `exception_level_filters`.

https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/delayed_job/plugin.rb#L15

Is there a way we can disable/filter the errors logged on job failure

Thanks!

Rob

**Comment by waltjones** [comment]
You are correct about needing an exception class, and it wouldn't need to be the original exception. The code could pass a new exception object of an appropriate type.

I don't know if or when that code will change, because it would change behavior for current users. The `:use_exception_level_filters => true` should be removed since it doesn't do anything.

To solve your issue now, I'd recommend adding a `before_process` handler. 

```
handler = proc do |options|
  raise Rollbar::Ignore if options[:message].include?("Job has failed and won't be retried anymore")
end

Rollbar.configure do |config|
  config.before_process << handler
end
```
There are a number of keys passed to the handler, but in this case the message string looks like the only useful one.

`before_process` handlers are described here:
https://docs.rollbar.com/docs/ruby#section-ignoring-items

The code for the actual logic applied to these handlers is here:
https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/notifier.rb#L343-L365

**Comment by RobWillison** [comment]
That's perfect thanks!
