### ISSUE TITLE
RSpec failures since 2.19.0

### ISSUE THREAD

**Issue by trev** [rollbar/rollbar-gem#887]
Let me preface by apologising for the limited information here but I've been hunting this down for days and have run out of time to perform further research. I do however want to get this out there to get a proper resolution. Happy to provide more information on request.

We use SemaphoreCI with Knapsack Pro. Our Rails 5.2.3 app uses Ruby 2.6.3.
Since updating from Rollbar 2.18.0 to [2.20.2](https://github.com/rollbar/rollbar-gem/releases/tag/v2.19.0) we started getting odd template and JSON related errors such as:

> ActionView::MissingTemplate:
> Missing template test/show, api/base/show with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :slim, :coffee, :jbuilder]}.

It shouldn't even be looking for a template since the spec code looks like:

```ruby
before do
  TestController.class_eval do
    def show
      render json: {tz: Time.zone.name}
    end
  end
end

it "uses the current user's time zone" do
  get :show, format: :json
  expect(parsed_response.fetch(:tz)).to eq('Brisbane')
end
```

* I can't get the same tests to fail by running the exact same test subsets with matching seed on local and on the SemaphoreCI (without Knapsack) by SSH'ing to the instance.
* The only way the same tests fail is when they're being ran automated on SemaphoreCI with Knapsack Pro: `KNAPSACK_PRO_CI_NODE_TOTAL=8 bundle exec rake knapsack_pro:queue:rspec`
* When I downgrade Rollbar back to pre 2.19.0 (e.g. 2.18.2), all specs pass.

All signs point to Knapsack and/or Rollbar gem issue and hoping for a bit of insight if anything comes to mind.

Any ideas? Tagging @arturt @ Knapsack Pro & @darkofabijan from SemaphoreCI.

**Comment by ArturT** [comment]
Hi @trev 

I guess this might be related to the running tests in Knapsack Pro Queue Mode and the fact that we reuse `RSpec::Core::Runner` to run a batch of tests fetched from a Queue. RSpec could have some problem with clearing RSpec world environment between running each batch of tests.

Please try some of this tips on separate branch:
https://github.com/KnapsackPro/knapsack_pro-ruby#why-when-i-use-queue-mode-for-rspec-then-my-tests-fail

For instance, run a binary version of knapsack_pro instead of a rake.

```
# Knapsack Pro Queue Mode run via binary
bundle exec knapsack_pro queue:rspec
```

You can also ensure you require rails_helper in your test files or in `.rspec` file.

BTW Do you override your `show` action whit this code? Is this your intention right?

```ruby
TestController.class_eval do
    def show
      render json: {tz: Time.zone.name}
    end
  end
```

Maybe you need `after` RSpec hook to get to previous code state to clean up after running test. 

Does original action render any template? Maybe try adding some `puts 'test'` in above override to see if it's actually called.


Does this error happen always on CI with Knapsack Pro or it's just happening there randomly? Maybe the order of loading tests does matter? 

You can also use full namespace `::TestController` instead of `TestController` to ensure you eval the proper controller.

**Comment by trev** [comment]
Thanks @ArturT - using the binary did the trick. Thanks for your time.
