### ISSUE TITLE
No method to assign issue owner

### ISSUE THREAD

**Issue by itsNikolay** [rollbar/rollbar-gem#899]
No method to set Issue Owner from the gem
(Like it can be set from browser)
It can be useful to take care about features you implemented
<img width="422" alt="Screenshot 2019-08-24 14 26 31" src="https://user-images.githubusercontent.com/786577/63636693-355bda80-c67b-11e9-8d14-ff6d00df0876.png">

**Comment by waltjones** [comment]
Not closing this for now, as maybe changes to the API could help enable this scenario. Here is why it can't be implemented under the current API.

While the SDKs send Occurrences, owners are set on Items, which are containers for a set of occurrences. If different occurrences grouped under the same item tried to set different owners, there's not a deterministic way to resolve the correct owner. Likewise if Rollbar's grouping algorithm changed the item assignment for an occurrence, the owner would still be based on the item, not the occurrence.

The way provided in the Rollbar API to set an owner is via:
PATCH https://api.rollbar.com/api/1/item/item_id

This requires the caller to know what item they want to reference, not just the occurrence.

These requirements can appear muddled because the current API for creating an occurrence is:
POST https://api.rollbar.com/api/1/item

This is not actually creating an item though. It creates an occurrence, and there is not a way to set the owner on that object. Trying to add it on this API endpoint leads to the problems described above.
