### ISSUE TITLE
nearly double Ruby memory usage if 900 Rollbar.error(e) invocations in a few hours

### ISSUE THREAD

**Issue by jpwynn** [rollbar/rollbar-gem#996]
Is it normal to see huge (nearly double) Ruby memory increase if Rollbar.error(e) is called an average of 6 or 7 times per minute?

Yesterday we started investigating Rollbar (gem 3.0.0) for use with our several Heroku apps. The first guinea pig was a Rails 4.2.11.1 app, Ruby 2.4.5, Puma web server (4.3.6), 3 workers, 1 thread, on Heroku 2X dynos.

In our evaulation, we enabled Rollbar.error(e) in several places, including some benign-exception 'rescue' blocks that are invoked frequently. This generated about 800 Rollbar events over a 2 hour period (average 6 per minute). And our max-memory nearly doubled from 675MB to 1150MB.

To my surprise, the use of Rollbar.error(e) seems to correlate with very significant memory bloat in Ruby memory.

So it seems even "swallowed" exceptions that would otherwise have no zero impact on user experience will significantly degrade user experience if Rollbar is enabled triggered an average of every 10 seconds.

To be precise, the benign exceptions do not, absent Rollbar, increase app memory use, which you can see in the Heroku memory metric screenshot attached, which shows the two hours before-and-after setting Rollbar's config.enabled to false ... the memory increase did not re-occur under similar traffic conditions once we disabled Rollbar by setting config.enabled = false

Heroku memory use before and after disabling rollbar:
<img width="248" alt="Metrics___Heroku" src="https://user-images.githubusercontent.com/446451/93400299-2c582100-f81b-11ea-8295-8fefceb50c62.png">

Approx same timeframe in Rollbar dashboard:
<img width="193" alt="Rollbar" src="https://user-images.githubusercontent.com/446451/93400326-3bd76a00-f81b-11ea-9fb4-04a0f19943d9.png">

**Comment by waltjones** [comment]
The gem creates the payload as a Ruby hash, which is then converted to a JSON string. The amount of memory used should correlate pretty closely with the size of hashes and strings created. This is all garbage collected by Ruby at some point, and the memory plateau (roughly from 9:00 - 10:00) _maybe_ looks like the normal case that memory was allowed to grow until it hit one of the GC limits. Or, maybe there are some objects not getting dereferenced correctly.

I'll set up a test here.

**Comment by waltjones** [comment]
@jpwynn I've tested, sending thousands of `Rollbar.error(e)` events and monitoring GC using `GC.stat`. https://ruby-doc.org/core-2.6.3/GC.html#method-c-stat

The GC was able to work efficiently, and I didn't see evidence of unfreed objects accumulating.

In my test, the memory didn't grow to the old object limit either. (Objects allocated during `Rollbar.error(e)` were freed by the minor GC.) However, that behavior in Ruby depends on the overall allocation pattern of objects in the app. Objects that remain referenced after several minor GCs will be marked as old and will only be freed during major GC. So it is possible for total memory usage to grow to your current old object/old malloc limit even if those objects were already freed. Whatever your ceiling is for memory usage, GC limits should be set to reflect that.

If you test with `GC.stat` and are seeing anything different, I'm happy to take a look and will try to replicate your conditions here.

**Comment by jpwynn** [comment]
What you say makes sense, and you can see on the Heroku memory chart I provided that it indeed plateaus when it hits the max. But FWIW on Heroku if memory plateaus "at/near" the GC limit that still causes lots of R14 errors because each little incremental bump in memory during operation generates a R14 which degrades performance, until some event like a dyno reboot.

So I guess my underlying quesiton is, is that level of memory allocation (several hundred MB) for 800 Rollbar events in quick succession typical?

**Comment by waltjones** [comment]
In Rails environments, it's pretty easy to generate large payloads because Rails backtraces are large. The final payload is limited to a half MB, but more than a MB of objects can get allocated. So yes, several hundred MB for 800 Rollbar events sounds plausible, and if it were all collected on the minor GC, it would get regularly freed and that would be fine.

Here are some ideas to mitigate.

It sounds like multiple minor GCs are happening during the processing of a single Rollbar event. This causes the Rollbar allocations to get pushed to the major GC. Reducing the amount of data processed for the payload could help by requiring fewer minor GCs and preventing objects from being marked as "old". The `backtrace_cleaner` Rollbar option can be used to filter or truncate the stack trace to focus on the parts relevant to your app and trim most of the bulk of it. Any `BacktraceCleaner` object can be passed, including the default Rails one. https://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html What makes this effective is that the stack is already smaller (maybe much smaller) before rollbar-gem tries to process it.

Another thing to look at is your GC settings. I think Heroku does give you access to these.

Set `RUBY_GC_OLDMALLOC_LIMIT` and `RUBY_GC_OLDMALLOC_LIMIT_MAX` lower. These values control when major GC runs, and in your case you want it to run sooner. 
 
For these settings, `GC.stat` will let you see their current values, and will help you confirm the new settings are being used.
